name = "bibliobay-rest-api"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 15, period = 10 }


[[r2_buckets]]
binding = "IMAGES"
bucket_name = "images"